server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    # false 表示eureka表示注册中心不自己注册自己
    register-with-eureka: false
    # false 表示自己是注册中心，我的职务是维护服务实例，并不需要检索服务器
    fetch-registry: false
    # 设置与eureka server 交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

